import {CONDICIONES} from '../efm-campo/organizacion.mjs';
import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
import * as perfil from '../efm-campo/perfil.mjs';import * as informes from '../efm-campo/informes.mjs';import * as ui from '../efm-campo/ui.mjs';import * as baremos from '../efm-campo/baremos.mjs';import * as medidas from '../efm-campo/medidas.mjs';
let root;class Element{constructor(dataset={}){this.dataset=dataset;this.events={};this.style={setProperty(){}};}addEventListener(k,fn){this.events[k]=fn;}focus(){}scrollIntoView(){}setAttribute(){}remove(){}closest(){return null;}querySelector(s){if(s==='[data-action=lap]')return null;if(s.startsWith('#')){const id=s.slice(1);if(!this.innerHTML?.includes('id="'+id+'"'))return null;return this.elements[id]??=new Element();}const m=s.match(/data-student="(.*?)"/);return m?new Element({student:m[1]}):null;}querySelectorAll(s){let regex,key;if(s==='[data-student]'){regex=/data-student="(.*?)"/g;key='student';}else if(s==='[data-test]'){regex=/data-test="(.*?)"/g;key='test';}else if(s.startsWith('[data-action]')){regex=/data-action="(.*?)"/g;key='action';}else if(s==='[data-key]'){regex=/data-key="(.*?)"/g;key='key';}else return [];return [...this.innerHTML.matchAll(regex)].map(m=>{const e=new Element({[key]:m[1]});this.buttons[key+':'+m[1]]=e;return e;});}set innerHTML(v){this.html=v;this.elements={};this.buttons={};}get innerHTML(){return this.html;}}
const document={getElementById(){return null;},createElement(){root=new Element();return root;},body:{append(){}}};
const roster=['ALFA','BRAVO','CHARLIE'].map((name,i)=>({id:'T'+i,nombre_completo:name,ciclo:'1ER CICLO',grado:'MY.',arma:'INF.',paralelo:'A',fecha_nacimiento:'1986-01-01',sexo:'M'}));
let source=fs.readFileSync(new URL('../efm-campo/app.mjs',import.meta.url),'utf8').replace(/^import .*;\n/gm,'').replaceAll('import.meta.url', '"file:///qa/app.mjs"').replace('export async function abrir','async function abrir');
const ctx={CONDICIONES,...perfil,...informes,...ui,...baremos,...medidas,document,localStorage:{getItem:()=>null},window:{},navigator:{},Intl,Date,Number,console,confirm:()=>true,setInterval:()=>1,clearInterval(){},crypto:{randomUUID:()=> '11111111-1111-1111-1111-111111111111'},descargar(){}};vm.createContext(ctx);vm.runInContext(source+';globalThis.openApp=abrir;',ctx);
await ctx.openApp({owner:'TEST',onClose(){},invoke:async()=>({cursantes:roster,registros:[]})});
root.buttons['student:T0'].onclick();
function key(k,target=root){let prevented=false;root.events.keydown({key:k,target,preventDefault(){prevented=true;}});return prevented;}
assert(key('ArrowDown'));assert(root.innerHTML.includes('<h2>MY. INF. BRAVO</h2>'));assert(key('ArrowDown'));assert(root.innerHTML.includes('<h2>MY. INF. CHARLIE</h2>'));key('ArrowDown');assert(root.innerHTML.includes('<h2>MY. INF. CHARLIE</h2>'));key('ArrowUp');assert(root.innerHTML.includes('<h2>MY. INF. BRAVO</h2>'));
assert.equal(key('ArrowDown',{closest:()=>({})}),false);assert(root.innerHTML.includes('<h2>MY. INF. BRAVO</h2>'));
root.querySelector('#efmc-peso').events.input({target:{value:'70'}});key('ArrowDown');assert(root.innerHTML.includes('<h2>MY. INF. BRAVO</h2>'));assert(root.innerHTML.includes('GUARDÁ LOS DATOS O LA MARCA'));
console.log('Teclado DOM: avance, retroceso, extremos, flechas nativas y borrador conservado: OK');
