const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{const d=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/docx'),Zip=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/jszip'),w=await import('../formato-militar/v1/word.js');w.configurarWord(d);
const cfg={superior:'SUPERIOR DE PRUEBA',unidad:'UNIDAD DE PRUEBA',seccion:'EMO/SEC-III',expedicion:1,iniciales:'SMM',lugar:'LOCALIDAD',fechaHora:'D-1 (0800)',titulo:'COMPROBACIÓN DEL FORMATO',nivel:'principal',jem:'XYZ',autenticador:'G-3',inicialesAut:'XYZ',distribucion:'Original: SUPERIOR DE PRUEBA'};
const titulos=['Primer nivel','Segundo nivel','Tercer nivel','Cuarto nivel','Quinto nivel','Sexto nivel'];let hijo;for(let i=5;i>=0;i--)hijo={titulo:titulos[i],texto:'Párrafo directo '+(i+1),hijos:[{texto:'Párrafo sin rótulo '+(i+1)},{sinRotulo:true,hijos:[{texto:'Párrafo anidado '+(i+1)}]},...(hijo?[hijo]:[])]};
const buffer=await d.Packer.toBuffer(w.crearWord({secciones:[hijo]},cfg)),zip=await Zip.loadAsync(buffer),documento=await zip.file('word/document.xml').async('string'),styles=await zip.file('word/styles.xml').async('string'),nums=await zip.file('word/numbering.xml').async('string');
for(const lvl of (nums.match(/<w:lvl\b[\s\S]*?<\/w:lvl>/g)||[]).filter(x=>x.includes('w:ascii="Arial"')))assert(lvl.includes('<w:u w:val="none"/>'),'Numeración sin subrayar en cada nivel');
for(let i=1;i<=6;i++){const estilo=styles.match(new RegExp('<w:style[^>]*w:styleId="Normal'+i+'"[\\s\\S]*?</w:style>'))[0];assert(estilo.includes('w:after="240"'));assert(estilo.includes('w:left="'+i*567+'"'));for(const pref of ['Párrafo directo','Párrafo sin rótulo','Párrafo anidado']){const p=(documento.match(/<w:p[ >][\s\S]*?<\/w:p>/g)||[]).find(x=>x.includes(pref+' '+i));assert(p.includes('w:val="Normal'+i+'"'),pref+' nivel '+i);assert(p.includes('w:after="240"'),'Separación efectiva del párrafo')}const titulo=styles.match(new RegExp('<w:style[^>]*w:styleId="MilitarTitulo'+i+'"[\\s\\S]*?</w:style>'))[0];assert(titulo.includes('w:after="240"'));if(i<3)assert(titulo.includes('w:val="single"'))}
const index=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8'),asset=index.match(/src="\.\/assets\/(index-[^"]+\.js)"/)[1],compiled=fs.readFileSync(path.join(__dirname,'../assets',asset),'utf8');assert(compiled.includes('runtime.js?v=exportacion20261001'));assert(fs.readFileSync(path.join(__dirname,'../formato-militar/v1/runtime.js'),'utf8').includes('word.js?v=espaciado20261001'));
if(process.argv[2]){fs.mkdirSync(process.argv[2],{recursive:true});fs.writeFileSync(path.join(process.argv[2],'seis-niveles.docx'),buffer)}console.log('OK: seis niveles, enumeración sin subrayar, espacio de una línea y párrafos directos/anidados alineados.');})().catch(e=>{console.error(e);process.exit(1)});
