const assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const d=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/docx'),Zip=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/jszip');const w=await import('../formato-militar/v1/word.js'),{textoOCA}=await import('../formato-militar/v1/oca.js');w.configurarWord(d);
const cfg={superior:'CE-I',unidad:'DIV.MEC.-1',seccion:'EMO/SEC-III',expedicion:3,iniciales:'SMM',lugar:'PAMPA LOMA',fechaHora:'D-15 (2300)',titulo:'ORDEN PREPARATORIA',numero:'01',nivel:'principal',jem:'XYZ',autenticador:'G3',inicialesAut:'SMM',firma:'EL COMANDANTE DE DIV.MEC.-1',distribucion:'Original: CE-I\nCopia 1-12: UU. DEP.\nCopia 13: ARCHIVO'};
const spec=process.argv[2]?JSON.parse(fs.readFileSync(process.argv[2])):{titulo:cfg.titulo,preliminares:[{rotulo:'OBJETO',texto:'Asunto breve.'},{rotulo:'CARTA',texto:'Carta Especial Calacoto, a escala 1:50.000, para el análisis espacial. Su empleo estandariza el trabajo. SIN DATO — verificar.'},{rotulo:'ANEXOS',texto:'Anexo A Calco de Operaciones y Anexo B Inteligencia de la Orden General de Operaciones No. 01/35. Esta documentación facilita la lectura.'}],secciones:[]};
const before=JSON.stringify(spec);assert.equal(textoOCA('OBJETO','La DIV. MEC. de prueba. Esta frase sobra.'),'La DIV. MEC. de prueba.');assert.equal(textoOCA('CARTA',spec.preliminares.find(p=>p.rotulo==='CARTA').texto),'Especial Calacoto, Esc. 1:50.000.');assert.equal(textoOCA('ANEXOS',spec.preliminares.find(p=>p.rotulo==='ANEXOS').texto),'“A” Calco de Operaciones.\n“B” Inteligencia.');assert.equal(textoOCA('ANEXOS','“A” Calco de Operaciones.\n“B” Inteligencia.'),'“A” Calco de Operaciones.\n“B” Inteligencia.');assert.equal(textoOCA('CARTA','Especial Otra Carta, Esc. 1:100.000.'),'Especial Otra Carta, Esc. 1:100.000.');assert.equal(textoOCA('OBJETO','Asunto propio. Explicación adicional.'),'Asunto propio.');assert.equal(textoOCA('ORGANIZACIÓN','Texto completo. Otra frase.'),'Texto completo. Otra frase.');
const buf=await d.Packer.toBuffer(w.crearWord(spec,cfg)),zip=await Zip.loadAsync(buf),xml=await zip.file('word/document.xml').async('string');const ps=xml.match(/<w:p[ >][\s\S]*?<\/w:p>/g)||[];
for(const label of ['OBJETO','CARTA','ANEXOS']){const p=ps.find(p=>p.includes('>'+label+'<'));assert(p.includes('w:left="2268" w:hanging="1701"'));assert(p.includes('w:pos="2268"'));if(label!=='ANEXOS')assert(p.includes('w:after="240"'))}
const b=ps.find(p=>p.includes('“B”'));assert(b.includes('w:left="2268"'));assert(!b.includes('w:hanging="1701"'));assert(xml.includes('w:w="5953"'));assert(xml.includes('w:pos="2097.9"'));assert.equal(JSON.stringify(spec),before);
if(process.argv[3])fs.writeFileSync(process.argv[3],buf);console.log('OK: OCA breve, anexos independientes, sangría 1/4 cm, distribución a la derecha y fuente intacta.');})().catch(e=>{console.error(e);process.exit(1)});
