-- ================================================================================
-- SIDECEME v2.9.409 — CARGA DE NOTAS EFM POR PLANILLA (Tcnl. Aguirre / My. Linares)
-- 100% ADITIVO: no borra ni modifica ninguna fila existente.
--   * evaluaciones_fisicas recibe 4 columnas NUEVAS y nullable. Las filas
--     históricas quedan con publicado = NULL → se siguen viendo igual que hoy.
--   * Tres tablas nuevas, con RLS activo y SIN políticas: solo la Edge Function
--     `efm-ops` (service_role) las lee y escribe.
-- ================================================================================

alter table public.evaluaciones_fisicas
  add column if not exists efm_id bigint generated by default as identity,
  add column if not exists carga_id bigint,
  add column if not exists publicado boolean,          -- NULL = histórico (visible), false = borrador, true = publicada
  add column if not exists actualizado_en timestamptz;

create unique index if not exists evaluaciones_fisicas_efm_id_uk on public.evaluaciones_fisicas (efm_id);
create index if not exists evaluaciones_fisicas_carga_idx on public.evaluaciones_fisicas (carga_id);

-- Cada planilla subida (una por archivo). Una evaluación = gestion+semestre+ciclo+tipo.
create table if not exists public.efm_cargas (
  id              bigint generated by default as identity primary key,
  gestion         integer  not null,
  semestre        smallint not null,
  ciclo           text     not null,
  tipo_evaluacion text     not null,
  categoria       text     not null,                  -- NORMAL | EXCELENCIA
  archivo         text,
  hoja            text,
  filas           integer  not null default 0,
  subido_por      text     not null,
  subido_por_nombre text,
  subido_en       timestamptz not null default now()
);

-- Conformidad del cursante sobre SU nota EFM publicada.
create table if not exists public.efm_confirmaciones (
  id              bigint generated by default as identity primary key,
  efm_id          bigint not null,
  cursante_id     text   not null,
  gestion         integer,
  semestre        smallint,
  ciclo           text,
  tipo_evaluacion text,
  nota_final      text,
  estado          text   not null default 'pendiente',  -- pendiente | confirmada | rechazada
  publicado_en    timestamptz,
  confirmada_en   timestamptz,
  observacion_cursante text,
  firma_cursante  text,
  huella_forense  jsonb,
  actualizado_en  timestamptz not null default now(),
  constraint efm_confirmaciones_estado_ck check (estado in ('pendiente','confirmada','rechazada'))
);
create unique index if not exists efm_confirmaciones_efm_uk on public.efm_confirmaciones (efm_id);
create index if not exists efm_confirmaciones_cur_idx on public.efm_confirmaciones (cursante_id);

-- Bitácora de correcciones (reclamos atendidos) y recargas que cambian una nota publicada.
create table if not exists public.efm_correcciones (
  id              bigint generated by default as identity primary key,
  efm_id          bigint not null,
  cursante_id     text   not null,
  origen          text   not null,                    -- correccion | recarga
  antes           jsonb,
  despues         jsonb,
  motivo          text,
  por_id          text   not null,
  por_nombre      text,
  en              timestamptz not null default now()
);
create index if not exists efm_correcciones_efm_idx on public.efm_correcciones (efm_id);

alter table public.efm_cargas         enable row level security;
alter table public.efm_confirmaciones enable row level security;
alter table public.efm_correcciones   enable row level security;
