import {catalogo} from './catalogo.js';
export const normalizar=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
export function iniciales(nombre){const p=String(nombre||'').trim().split(/\s+/).filter(Boolean);return (p.length>2?[p[0],...p.slice(-2)]:p).map(x=>x[0]).join('').toUpperCase()}
export function registroHoja(h,ctx={}){const g=ctx.g||(/^g[1-5]$/.test(ctx.campo)?ctx.campo:null)||({'i':'g1','ii':'g2','iii':'g3','iv':'g4','v':'g5'}[normalizar(ctx.seccion).replace(/^.*sec /,'').split(' ')[0]])||'g3';const id=h?.id||h;let plantilla=null;if(['aprecActiva','aprecOrientacion','aprecOps'].includes(id))plantilla=({'g1':'aprec-personal','g2':'aprec-inteligencia','g3':'aprec-operaciones','g4':'aprec-logistica','g5':'aprec-acgm'})[g];if(g==='g3')plantilla=({ivr:'orden-reconocimiento',prep1:'prep1',prep2:'prep2',prep3:'prep3',opord:'orden-operaciones'})[id]||plantilla;if(id==='anexoF7P1')plantilla=({g1:'plan-personal',g4:'plan-aspc'})[g]||null;return {g,hoja:id,paso:ctx.pasoDocumento||h?.num||'',plantilla,nivel:id==='anexoF7P1'?'anexo':'principal'}}
export function registroDirecto(tipo,g,ctx={}){const p=({apreciacion:{g1:'aprec-personal',g2:'aprec-inteligencia',g3:'aprec-operaciones',g4:'aprec-logistica',g5:'aprec-acgm',art:'aprec-artilleria',ing:'aprec-ingenieria',com:'aprec-comunicaciones',ada:'aprec-ada'},plan:{ing:'plan-ingenieria',com:'plan-comunicaciones',ada:'plan-ada',fuegos:'plan-fuegos',art:'apendice-fuegos'},documento:{log:'plan-logistica',engano:'plan-engano',recon:'orden-reconocimiento',movim:'orden-movimiento',calco:'calco'},anexo:{g1:'plan-personal',g4:'plan-aspc'},orden:{g3:'orden-operaciones'}})[tipo]?.[g]||null;return {g,hoja:tipo+':'+g,paso:ctx.pasoDocumento||'',plantilla:p,nivel:tipo==='anexo'?'anexo':p==='apendice-fuegos'?'apendice':'principal'}}
export function identidad(ctx,r){return JSON.stringify([ctx.ejercicio||'',ctx.unidad||'',r.g,r.hoja,r.paso,r.plantilla,r.nivel])}
export function contenidos(secciones){const out=[],repetidos=new Map();function visit(ns,path=[]){for(const n of ns||[]){const ruta=n.titulo?[...path,n.titulo]:path;if(n.texto||n.tabla||n.imagen||n.svg){const base=JSON.stringify(ruta),num=repetidos.get(base)||0;repetidos.set(base,num+1);out.push({id:base+':'+num,ruta:ruta.join(' / '),nodo:{...n,hijos:undefined},destino:null})}visit(n.hijos,ruta)}}visit(secciones);return out}
export function sugerencias(items,plantilla){const apartados=catalogo[plantilla]?.apartados||[];return items.map(it=>{const path=normalizar(it.ruta),leaf=normalizar(it.ruta.split(' / ').at(-1));let m=apartados.filter(a=>normalizar(a.ruta)===path);if(!m.length)m=apartados.filter(a=>normalizar(a.titulo)===leaf);return {...it,destino:m.length===1?m[0].ruta:null}})}
export function aplicarPlantilla(items,plantilla,cfg={}){const modelo=catalogo[plantilla];if(!modelo?.apartados.length)return null;const nodes=[],stack=[],lookup=new Map();for(const a of modelo.apartados){const n={titulo:a.titulo,hijos:[],ruta:a.ruta,nivel:a.nivel};stack.length=Math.min(stack.length,a.nivel-1);(stack.length?stack.at(-1).hijos:nodes).push(n);stack.push(n);lookup.set(a.ruta,n)}for(const it of items){const dest=lookup.get(cfg.asignaciones?.[it.id]||it.destino);if(!dest)throw Error('Asigne el contenido «'+it.ruta+'» a un apartado antes de exportar.');(dest.contenido??=[]).push({...it.nodo,titulo:'',sinRotulo:true})}function trim(ns){return ns.filter(n=>cfg.completo||n.nivel<=2||n.contenido?.length||n.hijos.some(h=>lookupCon(h))).map(n=>({...n,hijos:[...(n.contenido||[]),...trim(n.hijos)],texto:!n.contenido?.length&&!n.hijos.length?'[Pendiente de elaboración]':''}))}function lookupCon(n){return !!n.contenido?.length||n.hijos.some(lookupCon)}return trim(nodes)}
export function validarPadre(cfg,ctx,registro,registros){if(cfg.nivel==='principal')return null;const esperado={anexo:'principal',apendice:'anexo',agregado:'apendice'}[cfg.nivel];const padre=registros[cfg.padre];if(!padre||padre.ejercicio!==ctx.ejercicio||padre.unidad!==ctx.unidad||padre.nivel!==esperado)throw Error('Seleccione o registre el documento padre de esta unidad y ejercicio.');return padre}
